services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    image: phoenix
    container_name: phoenix
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5080:5080"
